<?php
$value = array (
  'wwwprefix' => 'http://localhost',
  'imgprefix' => 'http://localhost',
  'cssprefix' => 'http://localhost',
  'sitename' => '适合我',
  'sitetitle' => '专注·旅游团购',
  'abbreviation' => '适合我',
  'couponname' => '消费券',
  'currency' => '¥',
  'currencyname' => 'CNY',
  'timezone' => 'Etc/GMT-8',
  'invitecredit' => '5',
  'sideteam' => '15',
  'conduser' => 0,
  'partnerdown' => 0,
  'gzip' => 1,
  'kefuqq' => '',
  'kefumsn' => '',
  'mobileurl' => 'm.shihewo.com',
  'icp' => '京ICP备09033974号',
  'statcode' => '',
  'sinajiwai' => 'http://weibo.com/2119556367',
  'tencentjiwai' => 'http://t.qq.com/ShiHeWoLvYouWang',
  'googlemap' => 'ABQIAAAA2AvffIxV1wIzcowIa0MrCBQOsKH0-9GYawJEESviA14GZIZqFRRbd7JPBnDohYetGG3bNfR_S6JK1A',
  'renren' => 'http://www.renren.com/profile.do?id=366730138',
  'kaixin' => 'http://www.kaixin001.com/home/?uid=105826890',
  'seokeyword' => '旅游 团购 适合我 shihewo 酒店 门票',
);
?>